-- 033 down: kembalikan nama kolom ke Bahasa Indonesia (hanya untuk rollback darurat).
DO $$
DECLARE
  m TEXT[][];
  r TEXT[];
BEGIN
  m := ARRAY[
    ['members','full_name','nama_lengkap'],
    ['members','nickname','nama_panggilan'],
    ['members','gender','jenis_kelamin'],
    ['members','birth_place','tempat_lahir'],
    ['members','birth_date','tanggal_lahir'],
    ['members','photo_url','foto_url'],
    ['members','whatsapp_number','no_wa'],
    ['members','home_address','alamat_rumah'],
    ['members','village','desa'],
    ['members','region','daerah'],
    ['members','group_label','kelompok'],
    ['members','is_preacher','is_muballigh'],
    ['members','is_employed','is_kerja'],
    ['members','is_married','is_nikah'],
    ['members','height','tinggi_badan'],
    ['members','weight','berat_badan'],
    ['members','hobby','hobi'],
    ['members','occupation','pekerjaan'],
    ['members','mentoring_status','status_pembinaan'],
    ['members','is_active','status_aktif'],
    ['members','joined_date','tanggal_masuk'],
    ['members','left_date','tanggal_keluar'],
    ['members','education_level','jenjang_pendidikan'],
    ['members','school','sekolah'],
    ['members','major','jurusan'],
    ['members','education_start_year','tahun_mulai_pendidikan'],
    ['members','education_end_year','tahun_selesai_pendidikan'],
    ['pending_members','full_name','nama_lengkap'],
    ['pending_members','nickname','nama_panggilan'],
    ['pending_members','gender','jenis_kelamin'],
    ['pending_members','birth_place','tempat_lahir'],
    ['pending_members','birth_date','tanggal_lahir'],
    ['pending_members','photo_url','foto_url'],
    ['pending_members','whatsapp_number','no_wa'],
    ['pending_members','home_address','alamat_rumah'],
    ['pending_members','village','desa'],
    ['pending_members','region','daerah'],
    ['pending_members','is_married','is_nikah'],
    ['pending_members','occupation','pekerjaan'],
    ['pending_members','hobby','hobi'],
    ['pending_members','education_level','jenjang_pendidikan'],
    ['pending_members','school','sekolah'],
    ['pending_members','major','jurusan'],
    ['pending_members','education_start_year','tahun_mulai_pendidikan'],
    ['pending_members','education_end_year','tahun_selesai_pendidikan'],
    ['users','name','nama'],
    ['users','is_active','status_aktif'],
    ['groups','mentor','pembina'],
    ['groups','signatory','penandatangan'],
    ['groups','schedule','jadwal'],
    ['groups','is_active','status_aktif'],
    ['meetings','date','tanggal'],
    ['meetings','day','hari'],
    ['meetings','start_time','jam_start'],
    ['meetings','time','jam'],
    ['meetings','event','acara'],
    ['meetings','topic','materi'],
    ['meetings','notes','catatan'],
    ['meetings','target_categories','kategori_target'],
    ['announcements','date','tanggal'],
    ['announcements','day','hari'],
    ['announcements','time','jam'],
    ['announcements','event','acara'],
    ['announcements','topic','materi'],
    ['announcements','notes','catatan'],
    ['announcement_templates','template_name','nama_template'],
    ['announcement_templates','template_body','isi_template'],
    ['announcement_templates','is_active','status_aktif'],
    ['attendance','notes','catatan'],
    ['monitoring','date','tanggal'],
    ['monitoring','type','jenis'],
    ['monitoring','notes','catatan'],
    ['monitoring','follow_up','tindak_lanjut'],
    ['friday_schedules','date','tanggal'],
    ['friday_schedules','sermon_leader','khatib_imam'],
    ['friday_schedules','advisor','penasihat'],
    ['friday_schedules','parking_attendant','petugas_parkir'],
    ['friday_schedules','footwear_attendant','penata_sandal'],
    ['friday_schedules','notes','catatan'],
    ['kas_transactions','date','tanggal'],
    ['audit_logs','user_name','user_nama'],
    ['ai_usage','user_name','user_nama'],
    ['wa_queue','start_time','jam_start']
  ];
  FOREACH r SLICE 1 IN ARRAY m LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_name = r[1] AND column_name = r[2]
    ) THEN
      EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', r[1], r[2], r[3]);
    END IF;
  END LOOP;
END $$;
